### ISSUE TITLE
AdditionalLighting hash collision

### ISSUE THREAD

**Issue by TheRealElysium** [notfood/RimWorld-Miniaturisation#5]
Hash collision between Lighting_CeilingLamp_Blueprint_Install and Kibble: both have short hash 48559

Error on map load from Lighting_CeilingLamp.  I was using these lamps previously and did not get this error until AdditionalLighting support was added to my game.

**Comment by eskoONE** [comment]
That's weird. Try deleting the XML of it and try again. It is working for me without problems.

**Comment by eskoONE** [comment]
Just realized that's the fault of the DLL not the XML. Had a similar issue with the crematorium.

**Comment by biship** [comment]
I get this every time I load my game:
Hash collision between Lighting_CeilingLamp_Blueprint_Install and  Kibble: both have short hash 48559

**Comment by notfood** [comment]
Do you have EPOE? Their update recently caused hash issues.

**Comment by TheRealElysium** [comment]
Yeah I do, I'll try loading without it.

Update: Loaded a new map without EPOE and still got the same error, so I don't know what might be causing it.

It doesn't seem to have affected my game in any way yet, but I'll let you know if that changes.

**Comment by biship** [comment]
Same results for me. I can't find either Lighting_CeilingLamp_Blueprint_Install or Kibble in my save game, so I assume it's just the games assignment of hash to a name.  I can make and use KIbble without issue.

**Comment by notfood** [comment]
It appears that these overrides are not old save safe. I've gotten similar reports when people update old saves. I'll investigate further.

**Comment by notfood** [comment]
Can you guys test this branch? The DLL is in there. The difference is that this one queues a miniaturisation def cross load request instead of mangling its own before they exist, should be safer.

[postload-injection](https://github.com/notfood/RimWorld-Miniaturisation/tree/postload-injection)

Load order matters now, load after everything you wish to miniaturise. It's also not old save compatible. The hashes and names of the minified things change, make sure to erase any minified thing around or not play with an old save at all.

**Comment by TheRealElysium** [comment]
This appears to have fixed the issue, nice work.
