### ISSUE TITLE
Able to move, not able to assign work

### ISSUE THREAD

**Issue by biship** [notfood/RimWorld-Miniaturisation#8]
I created RedistHeat.xml and put it with the other XML's. 
output_log.txt shows: Miniaturisation :: Found RedistHeat (9)

For the medium cooler, I can Reinstall At... but can not right click and Prioritise Working On. It also seems my pawns won't move it on their own. It tried both with and without 'Cooler' (as I see it's also in CoreExtra.xml). What am I doing wrong?

**Comment by biship** [comment]
wow, I cant get XML to format. This is it:

```
<Defs>
    <Miniaturisation.MiniaturisationDef>
        <defName>MiniaturisationRedistHeat</defName>
        <requiredMod>RedistHeat</requiredMod>
        <targetsDefNames>
            <li>Heater</li>
            <li>Cooler</li>
            <li>RH_SmallCooler</li>
            <li>RH_MediumHeater</li>
            <li>RedistHeat_HeaterGlower</li>
            <li>RedistHeat_IndustrialHeater</li>
            <li>RedistHeat_IndustrialCooler</li>
            <li>RedistHeat_ExhaustPort</li>
            <li>RedistHeat_ActiveVent</li>
        </targetsDefNames>
    </Miniaturisation.MiniaturisationDef>
</Defs>
```

**Comment by TheRealElysium** [comment]
This is a known issue and it has to do with the comps of the building being to complex to handle for the current state of the mod.  You can get around this by uninstalling instead of reinstalling, and then installing once the item has been miniaturised.  The game might throw some errors at you while this happens but I've found you can just ignore them.

**Comment by biship** [comment]
ok, thanks
